apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: dst
  namespace: default
spec:
  mainApplicationFile: local:///Users/charmer/Developer/DiscretizedStreamTest/target/scala-2.13/dst.jar
  mainClass: com.github.oliverdding.dst.{TODO}
  mode: cluster
  restartPolicy:
    type: OnFailure
    onFailureRetries: 1
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  image: bitnami/spark:3.2.1
  imagePullPolicy: Always
  driver:
    cores: 1
    envVars:
      TODO: todo
    javaOptions: ' -Dlog4j2.formatMsgNoLookups=true -Dlog4j.formatMsgNoLookups=true '
    memory: 512m
    memoryOverhead: 512m
    serviceAccount: spark
  executor:
    cores: 2
    envVars:
      TODO: todo
    instances: 2
    javaOptions: ' -Dlog4j2.formatMsgNoLookups=true -Dlog4j.formatMsgNoLookups=true '
    memory: 512m
    memoryOverhead: 1g
  sparkConf:
    spark.driver.maxresultsize: 2G
    spark.eventLog.compress: "true"
    spark.eventLog.dir: local:///Users/charmer/Temporary/dst/spark-history
    spark.eventLog.enabled: "true"
    spark.sql.files.ignoreCorruptFiles: "true"
    spark.sql.files.ignoreMissingFiles: "true"
    spark.sql.session.timeZone: Asia/Shanghai
  type: Scala
